name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-17-jdk python3-pip git libncurses5 \
            libffi-dev libssl-dev build-essential libsqlite3-dev \
            libbz2-dev libreadline-dev liblzma-dev zlib1g-dev

      - name: Install buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Build APK
        run: |
    cd fallasapp
    buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fallasapp-apk
          path: bin/*.apk